Homework 2
================
Beibei Cao
2020-9-24

This is my solution to Homework 2.

``` r
# load libraries that will be used in this project
library(tidyverse)
library(readxl)
```

## Problem 1

Read the Mr. Trashwheel dataset.

``` r
trashwheel_df = 
  read_xlsx(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
    sheet = "Mr. Trash Wheel",
  range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
```

Read precipitation data\!

``` r
precip_2018 = 
  read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    skip = 1
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018) %>% 
  relocate(year)

precip_2017 = 
  read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2017 Precipitation",
    skip = 1
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2017) %>% 
  relocate(year)
```

Now combine the annual precipitation.

``` r
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

precip_df = bind_rows(precip_2018, precip_2017)

left_join(precip_df, month_df, by = "month")
```

    ## # A tibble: 24 x 4
    ##     year month total month_name
    ##    <dbl> <dbl> <dbl> <chr>     
    ##  1  2018     1  0.94 January   
    ##  2  2018     2  4.8  February  
    ##  3  2018     3  2.69 March     
    ##  4  2018     4  4.69 April     
    ##  5  2018     5  9.27 May       
    ##  6  2018     6  4.77 June      
    ##  7  2018     7 10.2  July      
    ##  8  2018     8  6.45 August    
    ##  9  2018     9 10.5  September 
    ## 10  2018    10  2.12 October   
    ## # … with 14 more rows

This dataset contains information from the Mr. Trashwheel trash
collector in Baltimore, Maryland. As trash enters the inner harbor, the
trashwheel collects that trash, and stores it in a dumpster. The dataset
contains information on year, month, and trash collected, including some
specific kinds of trash. There are a total of `344` rows in our final
dataset. Additional date sheets include month precipitation data.

``` r
sum(filter(precip_df, year == 2018)$total)
## [1] 70.33
median(filter(trashwheel_df, year == 2017)$sports_balls)
## [1] 8
```

The total precipitation in 2018 was `70.33 mm` and the median number of
sports balls in a dumpster in 2017 was `8`.

## Problem 2

Read and clean the NYC Transit data.

``` r
# read NYC csv
nyctransit_df = 
  read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() 

# check columns  
colnames(nyctransit_df)
# select wanted columns
nyctransit_df = nyctransit_df[,c(2:18,20,23)]
# preview and check which column with character variable (YES vs NO)
str(nyctransit_df)
# convert entry variable (col 17-18, 'entry' and 'vending') from character variable (YES vs NO) to logical variable
for (cl in c(17, 18)) {
  nyctransit_df[cl] = 
    ifelse(nyctransit_df[cl] == "YES", TRUE, FALSE)
}
```

Make sure the data frame looks like what we want.

``` r
# check result
str(nyctransit_df[17:18])
## tibble [1,868 × 2] (S3: tbl_df/tbl/data.frame)
##  $ entry  : logi [1:1868] TRUE TRUE TRUE TRUE TRUE TRUE ...
##  $ vending: logi [1:1868] TRUE TRUE TRUE TRUE TRUE TRUE ...

# preview dataset
colnames(nyctransit_df)
##  [1] "line"              "station_name"      "station_latitude" 
##  [4] "station_longitude" "route1"            "route2"           
##  [7] "route3"            "route4"            "route5"           
## [10] "route6"            "route7"            "route8"           
## [13] "route9"            "route10"           "route11"          
## [16] "entrance_type"     "entry"             "vending"          
## [19] "ada"
```

So far, we have loaded the NYC Transit dataset, cleaned the names of
columns, selected the desired columns and changed two columns, `entry`
and `vending`, from `YES/NO` character variables to `TRUE/FALSE` logical
variables. There are `1868` rows and `19` columns in the dataset. The
dataset contained the following variables: `line, station_name,
station_latitude, station_longitude, route1, route2, route3, route4,
route5, route6, route7, route8, route9, route10, route11, entrance_type,
entry, vending, ada`.

``` r
# keep distinct rows based on station name and line
uniq_station_df = distinct(nyctransit_df, line, station_name, .keep_all = TRUE)

# check the number of distinct stations as each row represent one distinct station
nrow(uniq_station_df)
## [1] 465

# stations that are ADA compliant
nrow(filter(uniq_station_df, ada == 'TRUE'))
## [1] 84
```

There are `465` distinct stations and `84` of them are are ADA
compliant.

``` r
# proportion of station entrances/exits without vending allow entrance
sum(nyctransit_df$vending == FALSE & nyctransit_df$entry == TRUE)/
  sum(nyctransit_df$vending == FALSE)
## [1] 0.3770492
```

There is `37.7%` station entrances/exits without vending allow entrance.

Reformat the data to simplify the process of counting the number of
distinct stations that serve the A train.

``` r
# convert route8:route11 into character variables
uniq_station_df[12:15] = sapply(uniq_station_df[12:15], as.character)

# reformat data so that route number and route name are distinct variables
reformed_df = pivot_longer(
  uniq_station_df,
  route1:route11,
  names_to = "route",
  values_to = "train"
)
```

``` r
# filter out stations that serve A train
reformed_df %>% 
  filter(train == "A") %>% 
  distinct(line, station_name) %>% 
  nrow()
## [1] 60
```

There are `60` distinct stations serve the A train.

``` r
# filter out statiosn that serve A train and are ADA compliant
reformed_df %>% 
  filter(train == "A", ada == TRUE) %>% 
  distinct(line, station_name) %>% 
  nrow()
## [1] 17
```

There are `17` distinct stations serve the A train that are ADA
compliant.

## Problem 3

Read and clean the data in `pols-month.csv`.

``` r
# import data and separate mon column into year, month, day and drop day column
pols_month_df = 
  read_csv(file = "./data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, c("year", "month", "day")) %>% 
  subset(select = -day) 

# replace month number with month name
pols_month_df$month = month.name[as.numeric(pols_month_df$month)]

# create a president variable taking values gop and dem, and remove prez_dem and prez_gop
pols_month_df$president = ifelse(pols_month_df$prez_dem == 1, 'dem', 'gop')
pols_month_df = subset(pols_month_df, select = -c(prez_dem, prez_gop)) %>% 
  relocate(year, month, president)
```

Check the pols-month data after cleaning

``` r
pols_month_df
```

    ## # A tibble: 822 x 9
    ##    year  month     president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <chr> <chr>     <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1 1947  January   dem            23      51     253      23      45     198
    ##  2 1947  February  dem            23      51     253      23      45     198
    ##  3 1947  March     dem            23      51     253      23      45     198
    ##  4 1947  April     dem            23      51     253      23      45     198
    ##  5 1947  May       dem            23      51     253      23      45     198
    ##  6 1947  June      dem            23      51     253      23      45     198
    ##  7 1947  July      dem            23      51     253      23      45     198
    ##  8 1947  August    dem            23      51     253      23      45     198
    ##  9 1947  September dem            23      51     253      23      45     198
    ## 10 1947  October   dem            23      51     253      23      45     198
    ## # … with 812 more rows

Read and clean the data in `snp.csv`.

``` r
# import data and separate date column into year, month, day and drop day column
snp_df = 
  read_csv(file = "./data/snp.csv") %>% 
  janitor::clean_names()  %>% 
  separate(date, c("month", "day", "year")) %>% 
  subset(select = -day) %>% 
  relocate(year)

# replace month number with month name
snp_df$month = month.name[as.numeric(snp_df$month)]
```

Check the snp data after cleaning.

``` r
snp_df
```

    ## # A tibble: 787 x 3
    ##    year  month    close
    ##    <chr> <chr>    <dbl>
    ##  1 2015  July     2080.
    ##  2 2015  June     2063.
    ##  3 2015  May      2107.
    ##  4 2015  April    2086.
    ##  5 2015  March    2068.
    ##  6 2015  February 2104.
    ##  7 2015  January  1995.
    ##  8 2014  December 2059.
    ##  9 2014  November 2068.
    ## 10 2014  October  2018.
    ## # … with 777 more rows

Read and clean the data in `unemployment.csv`.

``` r
# import data rename month columns
unemployment_df = 
  read_csv(file = "./data/unemployment.csv") %>% 
  janitor::clean_names()  
colnames(unemployment_df)[2:13] = month.name

# reformat the df to make months into a single variable
unemployment_df = pivot_longer(
  unemployment_df,
  January:December,
  names_to = 'month',
  values_to = 'unemployment' 
)

# change the type of year to character
unemployment_df[1] = sapply(unemployment_df[1], as.character)
```

Check the unemployment data after cleaning.

``` r
unemployment_df
```

    ## # A tibble: 816 x 3
    ##    year  month     unemployment
    ##    <chr> <chr>            <dbl>
    ##  1 1948  January            3.4
    ##  2 1948  February           3.8
    ##  3 1948  March              4  
    ##  4 1948  April              3.9
    ##  5 1948  May                3.5
    ##  6 1948  June               3.6
    ##  7 1948  July               3.6
    ##  8 1948  August             3.9
    ##  9 1948  September          3.8
    ## 10 1948  October            3.7
    ## # … with 806 more rows

Join the datasets by merging snp into pols, and merging unemployment
into the result.

``` r
merged_df = left_join(pols_month_df, snp_df, by = c('year', 'month'))
merged_df = left_join(merged_df, unemployment_df, by = c('year', 'month')) %>% 
  relocate(year, month, president, close, unemployment)
```

Check the `merged_df`.

``` r
merged_df
```

    ## # A tibble: 822 x 11
    ##    year  month president close unemployment gov_gop sen_gop rep_gop gov_dem
    ##    <chr> <chr> <chr>     <dbl>        <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1 1947  Janu… dem          NA           NA      23      51     253      23
    ##  2 1947  Febr… dem          NA           NA      23      51     253      23
    ##  3 1947  March dem          NA           NA      23      51     253      23
    ##  4 1947  April dem          NA           NA      23      51     253      23
    ##  5 1947  May   dem          NA           NA      23      51     253      23
    ##  6 1947  June  dem          NA           NA      23      51     253      23
    ##  7 1947  July  dem          NA           NA      23      51     253      23
    ##  8 1947  Augu… dem          NA           NA      23      51     253      23
    ##  9 1947  Sept… dem          NA           NA      23      51     253      23
    ## 10 1947  Octo… dem          NA           NA      23      51     253      23
    ## # … with 812 more rows, and 2 more variables: sen_dem <dbl>, rep_dem <dbl>

Get year ranges for each data set.

``` r
range(as.numeric(pols_month_df$year))
```

    ## [1] 1947 2015

``` r
range(as.numeric(snp_df$year))
```

    ## [1] 1950 2015

``` r
range(as.numeric(unemployment_df$year))
```

    ## [1] 1948 2015

``` r
range(as.numeric(merged_df$year))
```

    ## [1] 1947 2015

**pols\_month\_df**: contains `822` observations of `9` variables
related to the number of national politician who are democratic or
republican at any given time; the `president` variable indicates whether
the president was democratic (`dem`) or republican (`gop`); the variable
`year` in the dataframe ranges form `1947` to `2015`.

**snp\_df**: contains `787` observations of `3` variables related to
Standard & Poor’s stock market index (S\&P); the `close` variable
represents the closing values of the S\&P stock index on the associated
date; the variable `year` in the dataframe ranges form `1950` to `2015`.

**unemployment\_df**: contains `816` observations of `3` variables
related to unemployment; the `employment` variable represents the
percentage of unemployment in associated month of the year; the variable
`year` in the dataframe ranges form `1948` to `2015`.

**merged\_df**: joins information of the three dataframes described
above based on `year` and `month`; contains `822` observations of `11`
variables, including key variables `year, month, president, close,
unemployment`; the variable `year` in the dataframe ranges form `1947`
to `2015`.
